### PR TITLE
Fix misbehaviour of long tag and salary

### LINKED ISSUE #168: [PE-D] Long tag name.
Input a very long tag name causes it to overflow to other information.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: LeeEnEn/ped#1

### LINKED ISSUE #176: [PE-D] Extremely long salary result in tag being cut off
Try to add client with super long salary will result in date on the right to be covered and the salary will shoot out of the window.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: TeddYE/ped#3

### LINKED ISSUE #177: [PE-D] Long salary input
A very long salary input causes the bar to overflow.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: LeeEnEn/ped#3

### LINKED ISSUE #179: [PE-D] Very long email address
Email address gets cut off.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: LeeEnEn/ped#4

### LINKED ISSUE #183: [PE-D] Wrap text inconsistent
Long text wraps nicely when tags are of appropriate length.

But fails when tags have long values.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: LeeEnEn/ped#5

### PR DESCRIPTION
**Pull request by AD-NAP**
Long tags and salary causes the text-wrapping behaviour of the 
other labels to malfunction. No test cases were checked for 
salary and tag has a validity check of limited length. 

Bug found: Tags and salary misalign when multiple tags at max length
when GUI is too small. 

Let's 
* Add validation for tag and salary to limit to a reasonable length.
* Add test cases for salary and tag.
* Fix bug causing misalignment of salary and tags when it's all the max
length.

Should fix #168 , fix #176 , fix #177 , fix #179 and fix #183.

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Salary.java [hunk 1]
```diff
@@ -38,7 +38,7 @@ public Salary() {
      * @return A boolean stating if the string is valid or not.
      */
     public static boolean isValidSalary(String test) {
-        return test.matches(VALIDATION_REGEX);
+        return (test.matches(VALIDATION_REGEX) && test.length() <= 15);
```
Comment (Vishwanth2210) [inline src/main/java/seedu/address/model/person/Salary.java:41]: Nice, but this check can be added to the validation regex:
`"\\d{1,15}"`

**Review by Vishwanth2210 — CHANGES_REQUESTED** [review]
Looks good, just needs a small nit to be changed.

File: src/main/java/seedu/address/model/person/Salary.java (hunk 1 above)
Comment (AD-NAP) [reply src/main/java/seedu/address/model/person/Salary.java]: That's cleaner, will make the changes! Thanks!

**Review by Vishwanth2210 — APPROVED** [review]
Looks good to merge!
