### PR TITLE
Fix the way HustleBook parses numbers

### LINKED ISSUE #195: [PE-D] Inconsistent Error Message
￼
￼

￼

I think when dealing with 0 or negative number, error message should be consistent (in this case, it should be "the person index is invalid"

This mistake can be recreated in almost all functionalities that asks users to give index.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: albertsutz/ped#4

### LINKED ISSUE #209: [PE-D] Different responses received
- Have two clients that have the similar names, eg `Betsy A` and `Betsy B`
- flag Betsy, shows both clients
- enters 0 and 1000 gives different responses

0:

1000:

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: LeeEnEn/ped#7

### PR DESCRIPTION
**Pull request by kuanjr**
Right now, when the user inputs a number, it will show inconsistent error messages depending on the number they put.

For example, if they run `edit david p/123` and they are asked to give a confirmation of the index of the client to edit, the number "0" will give `Unknown command` as an error message instead of `The person index provided is invalid`. Error messages for wrong index is also inconsistent across `edit`, `delete` `find` and `meet` commands.

Let's,
 - Fix the way HustleBook recognises numbers
 - Fix the logic of the commands to ensure consistent error messages

Closes #209, Closes #195

### CODE REVIEW

File: src/main/java/seedu/address/commons/util/StringUtil.java [hunk 1]
```diff
@@ -65,4 +65,16 @@ public static boolean isNonZeroUnsignedInteger(String s) {
...
+     * Returns true if {@code s} represents an integer.
+     * e.g. -1, 0, 1, 2, 3, ...
+     * Returns true for +1, +2, +3, for consistency
+     * Returns false for any other non-null string input
+     * @param s
+     * @return
+     */
+    public static boolean isNumber(String s) {
+        return s.matches("\\d+(\\.\\d+)?");
+    }
```
Comment (Vishwanth2210) [inline src/main/java/seedu/address/commons/util/StringUtil.java:79]: Very nice regular expression. It would be better if that is kept as a constant named `NUMBER_VALIDATION_REGEX`

**Review by Vishwanth2210 — CHANGES_REQUESTED** [review]
Looks good to merge. Just a single nit that can be fixed.

File: src/main/java/seedu/address/commons/util/StringUtil.java (hunk 1 above)
Comment (kuanjr) [reply src/main/java/seedu/address/commons/util/StringUtil.java]: Ok. I've made and pushed the changes.

**Review by Vishwanth2210 — APPROVED** [review]
Looks good to merge!
