### PR TITLE
Fix find by char bug

### LINKED ISSUE #173: [PE-D] Duplicate names incorrectly handled
Somehow the program detects "magdalene" and "David Li" as "same name"? Perhaps due to the presence of substring "da"

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: geraldneo567/ped#1

### LINKED ISSUE #190: [PE-D] Bug: Find command
￼

￼

Looking at the User Guide, it is said that

Wrong functionality for points :
1. The order of the keywords does not matter. e.g. Hans Bo will match Bo Hans.
2. Only full words will be matched e.g. Han will not match Hans.
3. Clients matching at least one keyword will be returned (i.e. OR search). e.g. Hans Bo will return Hans Gruber, Bo Yang

Find David -> return David li
Find ibrahim -> return irfan Ibrahim
Find li him -> nothing

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: albertsutz/ped#2

### PR DESCRIPTION
**Pull request by kuanjr**
When searching by name, if you search "a", it will match all clients whose name contains "a", which should not be the case.

Let's,
 - Change the way HustleBook matches client's name

Closes #173, closes #190

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Name.java [hunk 1]
```diff
@@ -50,8 +53,46 @@ public boolean containsKeyword(String test) {
         if (test.equals("")) {
             return false;
         } else {
-            return this.fullName.toLowerCase().contains(test);
+            String[] keywords = test.split(" ");
+            String[] names = this.fullName.split(" ");
+            List<String> nameList = Arrays.asList(this.fullName.split(" "));
```
Comment (Vishwanth2210) [inline src/main/java/seedu/address/model/person/Name.java:58]: May I know why `this.fullName.split(" ")` is used? Why not use `names`?

**Review by Vishwanth2210 — CHANGES_REQUESTED** [review]
Looks good, just need to clarify something before approving.

File: src/main/java/seedu/address/model/person/Name.java (hunk 1 above)
Comment (kuanjr) [reply src/main/java/seedu/address/model/person/Name.java:58]: You are right I didn't notice that

**Review by Vishwanth2210 — APPROVED** [review]
